[graph]
all-features = true

[advisories]
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked = "deny"

[licenses]
confidence-threshold = 0.8
allow = [
  "Apache-2.0",
  "BSD-3-Clause",
  "BSL-1.0",
  "MIT",
  "Unicode-3.0",
]

[bans]
multiple-versions = "allow"
wildcards = "allow"
highlight = "all"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
