#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const tokenizerPath = path.join(ROOT, 'jscpd/packages/tokenizer/dist/index.mjs');
const outputPath = path.join(ROOT, 'src/formats.rs');

if (!fs.existsSync(tokenizerPath)) {
  console.error(`missing upstream tokenizer build: ${path.relative(ROOT, tokenizerPath)}`);
  console.error('run: pnpm --dir jscpd build');
  process.exit(1);
}

const { FORMATS, EXT_TO_FORMAT, getSupportedFormats } = await import(pathToFileURL(tokenizerPath));
const supportedFormats = getSupportedFormats();
const extensionFormats = [...EXT_TO_FORMAT.entries()];

const source = `use std::path::Path;

use crate::cli::FormatMappings;

// Generated by scripts/sync-formats.mjs from jscpd/packages/tokenizer/dist/index.mjs.
// Upstream getFormatByFile() uses first-writer-wins extension mappings and no
// built-in filename mappings; extensionless names are supported through
// --formats-names only.

pub const SUPPORTED_FORMATS: &[&str] = &[
${stringArray(supportedFormats)}
];

#[cfg(test)]
const EXTENSION_FORMATS_COUNT: usize = ${extensionFormats.length};

pub fn format_for_path<'a>(
    path: &Path,
    formats_exts: &'a FormatMappings,
    formats_names: &'a FormatMappings,
) -> Option<&'a str> {
    let file_name = path.file_name()?.to_string_lossy();
    if !formats_names.is_empty()
        && let Some(format) = formats_names.find_format_for_value(&file_name)
    {
        return Some(format);
    }

    let ext = path.extension()?.to_string_lossy();
    if !formats_exts.is_empty() {
        return formats_exts.find_format_for_value(&ext);
    }

    builtin_format_for_extension(&ext)
}

fn builtin_format_for_extension(extension: &str) -> Option<&'static str> {
    match extension {
${matchArms(extensionFormats)}
        _ => None,
    }
}

pub fn supported_formats() -> Vec<&'static str> {
    SUPPORTED_FORMATS.to_vec()
}

#[cfg(test)]
mod tests {
    use std::path::Path;

    use crate::cli::FormatMappings;

    #[test]
    fn maps_module_typescript_extensions_like_upstream() {
        let formats_exts = FormatMappings::default();
        let formats_names = FormatMappings::default();

        assert_eq!(
            super::format_for_path(Path::new("index.mts"), &formats_exts, &formats_names),
            Some("typescript")
        );
        assert_eq!(
            super::format_for_path(Path::new("index.cts"), &formats_exts, &formats_names),
            Some("typescript")
        );
    }

    #[test]
    fn maps_javascript_module_extensions_like_upstream() {
        let formats_exts = FormatMappings::default();
        let formats_names = FormatMappings::default();

        assert_eq!(
            super::format_for_path(Path::new("index.es"), &formats_exts, &formats_names),
            Some("javascript")
        );
        assert_eq!(
            super::format_for_path(Path::new("index.es6"), &formats_exts, &formats_names),
            Some("javascript")
        );
    }

    #[test]
    fn syncs_supported_format_surface_from_upstream() {
        assert_eq!(super::SUPPORTED_FORMATS.len(), ${supportedFormats.length});
        assert_eq!(super::EXTENSION_FORMATS_COUNT, ${extensionFormats.length});
        assert_eq!(super::supported_formats().first(), Some(&"abap"));
        assert!(super::supported_formats().contains(&"typescript"));
        assert!(super::supported_formats().contains(&"excel-formula"));
    }

    #[test]
    fn maps_long_tail_extensions_like_upstream() {
        let formats_exts = FormatMappings::default();
        let formats_names = FormatMappings::default();

        assert_eq!(
            super::format_for_path(Path::new("schema.g4"), &formats_exts, &formats_names),
            Some("antlr4")
        );
        assert_eq!(
            super::format_for_path(Path::new("component.bicep"), &formats_exts, &formats_names),
            Some("bicep")
        );
        assert_eq!(
            super::format_for_path(Path::new("formula.xlsx"), &formats_exts, &formats_names),
            Some("excel-formula")
        );
    }

    #[test]
    fn maps_header_extensions_like_upstream() {
        let formats_exts = FormatMappings::default();
        let formats_names = FormatMappings::default();

        assert_eq!(
            super::format_for_path(Path::new("foo.h"), &formats_exts, &formats_names),
            Some("c-header")
        );
        assert_eq!(
            super::format_for_path(Path::new("foo.hpp"), &formats_exts, &formats_names),
            Some("cpp-header")
        );
    }

    #[test]
    fn extensionless_names_require_formats_names_like_upstream() {
        let formats_exts = FormatMappings::default();
        let formats_names = FormatMappings::default();

        assert_eq!(
            super::format_for_path(Path::new("Makefile"), &formats_exts, &formats_names),
            None
        );

        let formats_names = FormatMappings::from_pairs(vec![(
            "makefile".to_string(),
            vec!["Makefile".to_string(), "GNUmakefile".to_string()],
        )]);

        assert_eq!(
            super::format_for_path(Path::new("Makefile"), &formats_exts, &formats_names),
            Some("makefile")
        );
    }
}
`;

fs.writeFileSync(outputPath, source);
console.log(`wrote ${path.relative(ROOT, outputPath)}`);
console.log(`formats=${supportedFormats.length} extensions=${extensionFormats.length}`);

function stringArray(values) {
  return values.map((value) => `    ${quote(value)},`).join('\n');
}

function matchArms(values) {
  return values.map(([left, right]) => `        ${quote(left)} => Some(${quote(right)}),`).join('\n');
}

function quote(value) {
  return JSON.stringify(value);
}
